---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangdongliang.
--- DateTime: 2018/5/8 17:48
---
local dialogTree = require('luagraphs.data.graph').create(0, true);
local function createDialogNode(choice, response, priority, onSelected)
    local newNode = {}

    if not choice then
        choice = ""
    end
    newNode.Choice = choice

    if not response then
        response = ""
    end
    newNode.Response = response

    if not priority then
        priority = math.huge
    end
    newNode.Priority = priority

    if not onSelected then
        onSelected = function() end
    end
    newNode.OnSelected = onSelected

    return newNode
end
local function dialogue()


    local start = createDialogNode("","欢迎光临我的朋友，货物都挑选好了么？")
    local Bill = createDialogNode("挑选好了。", "那我们就结算吧！", 1)
    local continueShop = createDialogNode("还没有挑选好呢","那你继续挑选吧！", 2)

    dialogTree:addEdge(start,Bill);
    dialogTree:addEdge(start,continueShop);

    local bargainFirstSuccess1 =  createDialogNode("能不能便宜些！老板？","也是老顾客了，给你个折扣价欢迎下次再来",1);
    local bargainFirstSuccess2 =  createDialogNode("老板，大老远的来一趟不容易啊。","也是老顾客了，给你个折扣价欢迎下次再来",2);
    local bargainFirstfailure3 =  createDialogNode("老板，大老远的来一趟不容易啊。","伙计，这已经是最低价了。",3);
    local bargainFirstfailure4 =  createDialogNode("能不能便宜些！老板？","最近物价飞涨，这已经是最低价了，不能再低了",4);

    dialogTree:addEdge(Bill,bargainFirstSuccess1);
    dialogTree:addEdge(Bill,bargainFirstSuccess2);
    dialogTree:addEdge(Bill,bargainFirstfailure3);
    dialogTree:addEdge(Bill,bargainFirstfailure4);

    local baigainSeccondSuccess1 = createDialogNode("老板，真是个爽快人，再给一个折扣价。","看着你有心买，我就在给你折上折",1);
    local baigainSeccondfailure2 = createDialogNode("老板，真是个爽快人，再给一个折扣价。","这已经是最低价了",2);

    dialogTree:addEdge(bargainFirstSuccess1,baigainSeccondSuccess1);
    dialogTree:addEdge(bargainFirstSuccess2,baigainSeccondSuccess1);
    dialogTree:addEdge(bargainFirstSuccess1,baigainSeccondfailure2);
    dialogTree:addEdge(bargainFirstSuccess2,baigainSeccondfailure2);

    local goodbye1 = createDialogNode("合作愉快老！真是个爽快人，谢谢您的优惠","欢迎下次惠顾",1);
    local goodbye2 = createDialogNode("那就按照这个价格算吧，下次可要给我优惠哦！","好的！欢迎下次惠顾");

    dialogTree:addEdge(baigainSeccondSuccess1,goodbye1);
    dialogTree:addEdge(baigainSeccondfailure2,goodbye1);
    dialogTree:addEdge(bargainFirstfailure3,goodbye2);
    dialogTree:addEdge(bargainFirstfailure4,goodbye2);

end

local function selectNode(node)

    local neighbors = dialogTree:adj(node)
    local sortNeighbors = neighbors.a;
    if neighbors then
        table.sort(sortNeighbors, function(c,d)      --
            return (c.w.Priority <= d.w.Priority)
        end)
        print("")
        --点击砍价按钮
        --动画播放完会返回是否成功砍价
        --我希望能返回一个index，帮我确定下一个节点是哪个
        return neighbors;
    end
    return nil;
end

local curNode

local function bargainDialogue(curnode,select)                 --播放完动画调用
    select = select or 1;
    local neighbors;
    if curnode ~= nil then
        neighbors = selectNode(curnode)
          --左闭右开，所以加1
        if select <= neighbors:size()then
            curNode = neighbors:get(select):to();
            print(curNode.Choice);       --玩家问
            curNode.OnSelected();
            if curNode.Response ~= "" then
                print(curNode.Response);                                    --店长回
            end
        else
            print("没有对应的对话节点，请检查节点设置")
        end

    end
end

dialogue();
curNode = dialogTree:vertexAt(1); --设置当前节点为首节点
if curNode.Response ~= "" then
    print(curNode.Response);   --店老板进门会说客套话
end

bargainDialogue(curNode,1);
bargainDialogue(curNode,3);
bargainDialogue(curNode);
bargainDialogue(curNode,1);
