---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangdongliang.
--- DateTime: 2018/5/8 15:06
---



local DialogTree = require('luagraphs.data.graph').create(0, true) -- true means it is directed

local bit = require("bit")
print(bit.lshift(2,30))

local function createDialogNode(choice, response, priority, onSelected)
    local newNode = {}

    if not choice then
        choice = ""
    end
    newNode.Choice = choice

    if not response then
        response = ""
    end
    newNode.Response = response

    if not priority then
        priority = math.huge
    end
    newNode.Priority = priority

    if not onSelected then
        onSelected = function() end
    end
    newNode.OnSelected = onSelected

    --DialogTree:AddVertex(newNode)

    return newNode
end

local start = createDialogNode("", "Hello there! How are you?")

local goodFeel = createDialogNode("I'm well, thank you.", "That's great! Glad to hear it!", 1);
local mehFeel = createDialogNode("Meh, been better.", "I'm sorry to hear that.", 2);
local badFeel = createDialogNode("I'm grumpy.", "I'm sorry to hear that.", 3);

DialogTree:addEdge(start, goodFeel)
DialogTree:addEdge(start, mehFeel)
DialogTree:addEdge(start, badFeel)

local who = createDialogNode("So who are you anyway?", "I'm the dialog guy of course!")

DialogTree:addEdge(goodFeel, who)
DialogTree:addEdge(mehFeel, who)
DialogTree:addEdge(badFeel, who)

local function exitDialog()
    print("退出对话")
end

local investigate = createDialogNode("Investigate", "", 1)
local goodbye = createDialogNode("Goodbye!", "", 2, exitDialog)

DialogTree:addEdge(who, investigate)
DialogTree:addEdge(who, goodbye)

print(DialogTree:vertexCount()) -- return 6


local color
color = createDialogNode("What's your favorite color?", "white", 1, function()
    DialogTree:removeEdge(investigate, color)
    local adj_v = DialogTree:adj(investigate)
    for k = 0,adj_v:size()-1 do
        DialogTree:addEdge(color, adj_v:get(k):to())
    end
end)
local long
long = createDialogNode("How long have you been here?", "A while.", 2, function()
    DialogTree:removeEdge(investigate, long)
    local adj_v = DialogTree:adj(investigate)
    for k = 0,adj_v:size()-1 do
        DialogTree:addEdge(long, adj_v:get(k):to())
    end
end)

DialogTree:addEdge(investigate, color)
DialogTree:addEdge(investigate, long)

local neverMind
neverMind = createDialogNode("Nevermind.", "Is there anything else I can do for you?", 3, function()
    local investigateNeighbors = DialogTree:adj(investigate)
    if investigateNeighbors:size() <= 1 then
        DialogTree:removeEdge(neverMind, investigate)
    end
end)



DialogTree:addEdge(investigate, neverMind)
DialogTree:addEdge(neverMind, investigate)
DialogTree:addEdge(neverMind, goodbye)

print(DialogTree:vertexCount())


local function selectNode(node)
    local selectNum = 0;
    if node.Response ~= "" then
        print("Npc:" ..node.Response)
    end
    local neighbors = DialogTree:adj(node)
    if neighbors then
        table.sort(neighbors, function(a,b)
            return a.Priority <= b.Priority
        end)
        --print("玩家：")
        local nextNode
        for index = 0, neighbors:size()-1 do
            nextNode = neighbors:get(index):to()
            --local choiceButton = DialogGui:FindFirstChild("Choice"..index)
            --choiceButton.Visible = true
            --print(nextNode.Choice)
            --绑定点击事件
        end
        nextNode = neighbors:get(selectNum):to()
        nextNode.OnSelected()
        print("玩家选择："..nextNode.Choice)
        selectNode(nextNode)


    end
end
selectNode(start)

--运行结果会有报空错误，是由于在没有邻接节点时也调用了事件，后面采用绑定事件就不会发生了。



