---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangdongliang.
--- DateTime: 2018/11/6 21:52
---

a = {[1] = 2,[2]=3,[3]=4,[4] = 5,[5] = 6}
for k,v in pairs(a)do
    print(k,v)
end

local alarmtime = os.time({year = 2018,month = 11,day = 19,hour=22,min=0,sec=0});
local curtime = os.time();
print(alarmtime - curtime)
--print(MyQueue:dequeue());
Account = {balance = 0}

function Account:new(o,val)
    o = o or {}
    self.__index = self
    self.Val = val;
    setmetatable(o,self)
    return o;
end
function Account:deposit(v)
    self.balance = self.balance + v;
end
function Account:withdraw(v)
    if(v>self.balance)then
        error "insufficient funds"
    end
    self.balance = self.balance - v;
end

SpecialAccount = Account:new()

s = SpecialAccount:new({limit=1000})

function SpecialAccount:withdraw(v)
    if v - self.balance >= self:getLimit()then
        error "insufficient funds"
    end
    self.balance = self.balance - v;
end
function SpecialAccount:getLimit()
    return self.limit or 0;
end

s:deposit(1000);
print("你的存款为",s.balance);
s:withdraw(500);
print("你的存款为",s.balance);
s:withdraw(1000);
print("你的存款为",s.balance);
d = {}
d = Account:new(d,1);
d:deposit(500);

e = {}
e = Account:new(e,2);
e:deposit(500);
print("e的存款为",e.Val);
print("d的存款为",d.Val);