---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangdongliang.
--- DateTime: 2018/11/10 9:23
---

--单向队列
local Node = {item = 0,next = nil};
function Node:new(o)
    o = o or {}
    setmetatable(o,Node)
    return o;
end

local Queue = {first = nil,last = nil,N = 0}
Queue.__index = Queue;

function Queue:new(o)
    o = o or {}
    setmetatable(o,Queue)
    return o;
end
function Queue:isEmpty()
    return self.N == 0;
end

function Queue:size()
    return self.N;
end
--向表尾添加元素
function Queue:enqueue(item)
    local oldLast = self.last;
    self.last = Node.new();
    self.last.item = item;
    self.last.next = nil;
    if(self:isEmpty())then
        self.first = self.last;
    else
        oldLast.next = self.last;
    end
    self.N = self.N+1;
end
--从表头删除元素
function Queue:dequeue()
    local item = self.first.item;
    self.first = self.first.next;
    if(self:isEmpty())then
        self.last = nil;
    end
    self.N = self.N - 1;
    return item;
end

return Queue
