---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangdongliang.
--- DateTime: 2018/10/30 16:57
---
ActivityItemInfo = {};
ActivityItemInfo.m_type = 0;
ActivityItemInfo.m_completeTime = 0; -- 参加次数
ActivityItemInfo.m_validTime = 0; -- 有效次数

local itemInfoMt = { }
itemInfoMt.__index = ActivityItemInfo
itemInfoMt.__newindex = function(_,k,v)
    ActivityItemInfo[k] = v;
end
function ActivityItemInfo:New()
    local t = { };
    -- 设置元表
    setmetatable(t, itemInfoMt)
    return t;
end

a = ActivityItemInfo:New();
b = ActivityItemInfo:New();
--由于没有调用了__newindex，所以完成了赋值
a.m_type = 1;
--b.m_type = 2;
print(a.m_type);
print(b.m_type)

c = "Chect_12"
local k,v = string.match(c,"(%a+)_(%d+)")
print(k,v)
--for k,v in string.gmatch(c,"(%a+)_(%d+)") do
--    print(k,v)
--end
for i = 1, 0 do
    print("ok")
end
function table.clear(self)
    for k in next,self do
        rawset(self,k,nil)
    end
end
local cleartest = {1,2,3}
table.clear(cleartest)
print(#cleartest)
print(math.modf(15,2))
print(string.match("df1","%d"))